apiVersion: v1
kind: Secret
metadata:
  name: venomous-ia-secret
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  USERNAME_PYTHON: admin
  PASSWORD_PYTHON: 123456
  BASE_URL: https://ollama.house-software.com.br
  MODEL: deepseek-r1:1.5b